In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.animation as animation


import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff


# Step 1: Loading Dataset

In [2]:
# df = pd.read_csv('Data\FS_Classification_AMZN_Historical_Quarterly_2009_2022_With_Fundamental_Data_Economic_Indicators.csv')
df = pd.read_csv('Data\FS_Classification_AMZN_Historical_Quarterly_2023_Onwards_With_Fundamental_Data_Economic_Indicators.csv')



# Removing leading and trailing spaces from column names
df.columns = df.columns.str.strip()

# Using a regular expression to replace multiple spaces with a single space in all column names
df.columns = df.columns.str.replace(r'\s+', ' ', regex=True)  

# # Dropping columns that are not needed
df.drop(["Date", "Year"], axis=1, inplace=True)



# Step 2: Overview of Dataset

In [3]:
num_of_rows = len(df)
print(f"The number of rows is {num_of_rows}")
print('\n')

df.info()

The number of rows is 7


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 35 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Open                            7 non-null      float64
 1   High                            7 non-null      float64
 2   Low                             7 non-null      float64
 3   Close                           7 non-null      float64
 4   MA_21                           7 non-null      float64
 5   Stochastic_Oscillator           7 non-null      float64
 6   ATR                             7 non-null      float64
 7   Cumulative_Return               7 non-null      float64
 8   Volatility                      7 non-null      float64
 9   Price_Gap                       7 non-null      float64
 10  Durable_Goods_Orders_Quarterly  7 non-null      float64
 11  Federal_Funds_Rate_Quarterly    7 non-null      float64
 12  Retail_Sales_Q

In [4]:
df.head()

Open        High         Low       Close       MA_21  \
0   85.459999  114.000000   81.430000  103.290001   94.574424   
1  102.300003  131.490005   97.709999  130.360001  109.537804   
2  130.820007  145.860001  123.040001  127.120003  133.134233   
3  127.279999  155.630005  118.349998  151.940002  137.242933   
4  151.539993  181.699997  144.050003  180.380005  162.643059   

   Stochastic_Oscillator       ATR  Cumulative_Return  Volatility  Price_Gap  \
0              57.035177  2.624101          38.002209    4.137302  -0.064516   
1              74.222630  2.199527          47.961738    3.658027   0.270968   
2              52.517575  2.589117          46.769686    3.425982   0.140317   
3              69.167466  2.602857          55.901400    4.435649   0.082222   
4              71.302744  2.503677          66.364978    4.172435   0.187542   

   ...  changeInInventory  cashflowFromInvestment  surprisePercentage  \
0  ...      -3.710000e+08           -1.580600e+10             47.6190   
1  ...       2.373000e+09           -9.673000e+09             85.7143   
2  ...      -8.080000e+08           -1.175300e+10             62.0690   
3  ...      -2.643000e+09           -1.260100e+10             25.0000   
4  ...      -1.776000e+09           -1.786200e+10             19.5122   

    grossProfit  totalRevenue  costOfRevenue  costofGoodsAndServicesSold  \
0  4.340300e+10  1.266050e+11   8.320200e+10                6.779100e+10   
1  4.869300e+10  1.335520e+11   8.485900e+10                6.937300e+10   
2  5.261000e+10  1.421830e+11   8.957300e+10                7.502200e+10   
3  3.940100e+10  1.693280e+11   1.299270e+11                9.255300e+10   
4  5.661700e+10  1.425950e+11   8.597800e+10                7.263300e+10   

   incomeTaxExpense  Quarterly_Return  Hybrid_Price_Movement_Class  
0      9.480000e+08          0.262078                            3  
1      8.040000e+08         -0.024854                            2  
2      2.306000e+09          0.195249                            3  
3      3.042000e+09          0.187179                            3  
4      2.467000e+09          0.071349                            3  

[5 rows x 35 columns]

# Step 3: EDA - Missing Values Analysis 

## Step 3)i): EDA - Show Missing Values in each Column

In [5]:
def display_columns_with_null_values(df: pd.DataFrame):
    """
    Displays the total number of null values for each column in the dataframe,
    showing only columns that have null values.
    
    Parameters:
    - df (pd.DataFrame): The dataframe to be checked for null values.
    
    Returns:
    - None: Prints the columns with null values and their counts.
    """
    
    # Get total null values in each column
    total_null_values = df.isnull().sum()
    
    # Filter out columns that don't have any null values
    columns_with_null = total_null_values[total_null_values > 0].sort_values(ascending=False)
    
    # Check if there are any columns with null values
    if not columns_with_null.empty:
        print('-' * 64)
        print("Total null values in each column (only columns with null values)")
        print('-' * 64)
        print(columns_with_null)
    else:
        print('-' * 64)
        print("Total null values in each column (only columns with null values)")
        print('-' * 64)
        print("No columns have null values.")

In [6]:
# Get percentage of null values in each column
null_values_percentage = df.isnull().mean().round(4).mul(100).sort_values(ascending=False)
print('-' * 44)
print("Percentage(%) of null values in each column")
print('-' * 44)
print(null_values_percentage)
print('\n')

# Get total null values in each column
display_columns_with_null_values(df)


--------------------------------------------
Percentage(%) of null values in each column
--------------------------------------------
Open                              0.0
cashflowFromInvestment            0.0
otherCurrentLiabilities           0.0
changeInOperatingLiabilities      0.0
changeInOperatingAssets           0.0
capitalExpenditures               0.0
changeInReceivables               0.0
changeInInventory                 0.0
surprisePercentage                0.0
totalCurrentLiabilities           0.0
grossProfit                       0.0
totalRevenue                      0.0
costOfRevenue                     0.0
costofGoodsAndServicesSold        0.0
incomeTaxExpense                  0.0
Quarterly_Return                  0.0
currentAccountsPayable            0.0
otherCurrentAssets                0.0
High                              0.0
Volatility                        0.0
Low                               0.0
Close                             0.0
MA_21                         

## Step 3)ii): EDA - Handling Missing Values

In [7]:
# Fill Null Values in the Remaining Columns with the average of the column
numeric_df = df.select_dtypes(include=[np.number]) # Select only numeric columns
numeric_df.fillna(numeric_df.mean(), inplace=True)  # Fill missing values in numeric columns with the column mean
df[numeric_df.columns] = numeric_df # Merge back with non-numeric columns if needed

# Get total null values in each column
display_columns_with_null_values(df)


----------------------------------------------------------------
Total null values in each column (only columns with null values)
----------------------------------------------------------------
No columns have null values.


# Step 4: EDA - Duplicate Values Analysis 

## Step 4)i): EDA - Show Duplicate Values Rows

In [8]:
# Get percentage of duplicate rows
total_rows = len(df)
duplicate_rows = df.duplicated().sum()
duplicate_percentage = (duplicate_rows / total_rows) * 100

print('-' * 48)
print("Percentage(%) of duplicate rows in the DataFrame")
print('-' * 48)
print(f"{duplicate_percentage:.2f}%")
print('\n')

# Get total number of duplicate rows
print('-' * 30)
print("Total number of duplicate rows")
print('-' * 30)
print(duplicate_rows)


------------------------------------------------
Percentage(%) of duplicate rows in the DataFrame
------------------------------------------------
0.00%


------------------------------
Total number of duplicate rows
------------------------------
0


# Step 5): EDA - BackTesting

In [9]:
import joblib
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

# Load the saved model
joblib_file = "Model/random_forest_model_pipeline.joblib"
loaded_model = joblib.load(joblib_file)


# Extract features and actual labels
features = df.drop(columns=['Hybrid_Price_Movement_Class']) 
actual_labels = df['Hybrid_Price_Movement_Class']

# Make predictions using the loaded model
predicted_labels = loaded_model.predict(features)

# Add predictions to the original DataFrame as a new column
df['Hybrid_Price_Movement_Class_Prediction'] = predicted_labels

df.head(15)  

Open        High         Low       Close       MA_21  \
0   85.459999  114.000000   81.430000  103.290001   94.574424   
1  102.300003  131.490005   97.709999  130.360001  109.537804   
2  130.820007  145.860001  123.040001  127.120003  133.134233   
3  127.279999  155.630005  118.349998  151.940002  137.242933   
4  151.539993  181.699997  144.050003  180.380005  162.643059   
5  180.789993  199.839996  166.320007  193.250000  182.068685   
6  193.490005  201.199997  151.610001  186.330002  182.434695   

   Stochastic_Oscillator       ATR  Cumulative_Return  Volatility  Price_Gap  \
0              57.035177  2.624101          38.002209    4.137302  -0.064516   
1              74.222630  2.199527          47.961738    3.658027   0.270968   
2              52.517575  2.589117          46.769686    3.425982   0.140317   
3              69.167466  2.602857          55.901400    4.435649   0.082222   
4              71.302744  2.503677          66.364978    4.172435   0.187542   
5              60.945101  2.844399          71.100075    3.840863   0.256349   
6              57.869881  3.823794          68.554086    6.970830   0.227343   

   ...  cashflowFromInvestment  surprisePercentage   grossProfit  \
0  ...           -1.580600e+10           47.619000  4.340300e+10   
1  ...           -9.673000e+09           85.714300  4.869300e+10   
2  ...           -1.175300e+10           62.069000  5.261000e+10   
3  ...           -1.260100e+10           25.000000  3.940100e+10   
4  ...           -1.786200e+10           19.512200  5.661700e+10   
5  ...           -2.213800e+10           22.330100  5.955300e+10   
6  ...           -5.660934e+09           32.289969  2.204919e+10   

   totalRevenue  costOfRevenue  costofGoodsAndServicesSold  incomeTaxExpense  \
0  1.266050e+11   8.320200e+10                6.779100e+10      9.480000e+08   
1  1.335520e+11   8.485900e+10                6.937300e+10      8.040000e+08   
2  1.421830e+11   8.957300e+10                7.502200e+10      2.306000e+09   
3  1.693280e+11   1.299270e+11                9.255300e+10      3.042000e+09   
4  1.425950e+11   8.597800e+10                7.263300e+10      2.467000e+09   
5  1.478390e+11   8.828600e+10                7.378500e+10      1.767000e+09   
6  5.619616e+10   3.865521e+10                3.335348e+10      3.863387e+08   

   Quarterly_Return  Hybrid_Price_Movement_Class  \
0          0.262078                            3   
1         -0.024854                            2   
2          0.195249                            3   
3          0.187179                            3   
4          0.071349                            3   
5         -0.035809                            2   
6          0.077790                            3   

   Hybrid_Price_Movement_Class_Prediction  
0                                       3  
1                                       3  
2                                       3  
3                                       3  
4                                       3  
5                                       1  
6                                       3  

[7 rows x 36 columns]

In [10]:
# Calculate performance metrics for multi-class classification
accuracy = accuracy_score(actual_labels, predicted_labels)
precision = precision_score(actual_labels, predicted_labels, average='macro')  # Average for multi-class
recall = recall_score(actual_labels, predicted_labels, average='macro')
conf_matrix = confusion_matrix(actual_labels, predicted_labels)

# Display the results
# print(f'Accuracy: {accuracy:.4f}')
# print(f'Precision (Macro): {precision:.4f}')
# print(f'Recall (Macro): {recall:.4f}')
print('Confusion Matrix:')
print(conf_matrix)
print('\nClassification Report:')
print(classification_report(actual_labels, predicted_labels))


Confusion Matrix:
[[0 0 0]
 [1 0 1]
 [0 0 5]]

Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       0.00      0.00      0.00         2
           3       0.83      1.00      0.91         5

    accuracy                           0.71         7
   macro avg       0.28      0.33      0.30         7
weighted avg       0.60      0.71      0.65         7

