In [21]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.animation as animation


import plotly.express as px
import plotly.graph_objects as go
import plotly.figure_factory as ff


# Step 1: Loading Dataset

In [22]:
# df = pd.read_csv('Data\FS_Classification_AMZN_Historical_Quarterly_2009_2022_With_Fundamental_Data_Economic_Indicators.csv')
df = pd.read_csv('Data\FS_Classification_AMZN_Historical_Quarterly_2023_Onwards_With_Fundamental_Data_Economic_Indicators.csv')



# Removing leading and trailing spaces from column names
df.columns = df.columns.str.strip()

# Using a regular expression to replace multiple spaces with a single space in all column names
df.columns = df.columns.str.replace(r'\s+', ' ', regex=True)  

# # Dropping columns that are not needed
df.drop(["Date", "Year"], axis=1, inplace=True)



# Step 2: Overview of Dataset

In [23]:
num_of_rows = len(df)
print(f"The number of rows is {num_of_rows}")
print('\n')

df.info()

The number of rows is 7


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 36 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Open                            7 non-null      float64
 1   High                            7 non-null      float64
 2   Low                             7 non-null      float64
 3   Close                           7 non-null      float64
 4   Volume                          7 non-null      int64  
 5   MA_21                           7 non-null      float64
 6   RSI                             7 non-null      float64
 7   MACD                            7 non-null      float64
 8   Stochastic_Oscillator           7 non-null      float64
 9   ATR                             7 non-null      float64
 10  Momentum_21                     7 non-null      float64
 11  OBV                             7 non-null      int64  
 12  Cumulative_Ret

In [24]:
df.head()

Open        High         Low       Close      Volume       MA_21  \
0   85.459999  114.000000   81.430000  103.290001  4237140900   94.574424   
1  102.300003  131.490005   97.709999  130.360001  3899624000  109.537804   
2  130.820007  145.860001  123.040001  127.120003  3389452900  133.134233   
3  127.279999  155.630005  118.349998  151.940002  3181680200  137.242933   
4  151.539993  181.699997  144.050003  180.380005  2700335000  162.643059   

         RSI      MACD  Stochastic_Oscillator       ATR  ...  \
0  54.283704  1.411384              57.035177  2.624101  ...   
1  62.979858  3.396109              74.222630  2.199527  ...   
2  53.048983 -2.481221              52.517575  2.589117  ...   
3  57.185846  2.782032              69.167466  2.602857  ...   
4  59.673912  2.546693              71.302744  2.503677  ...   

   capitalExpenditures  changeInReceivables  changeInInventory  \
0         1.420700e+10         1.521000e+09      -3.710000e+08   
1         1.145500e+10        -5.167000e+09       2.373000e+09   
2         1.247900e+10        -1.304035e+09      -8.080000e+08   
3         1.458800e+10        -1.304035e+09      -2.643000e+09   
4         1.492500e+10        -1.304035e+09      -1.776000e+09   

   surprisePercentage   grossProfit  costOfRevenue  \
0             47.6190  4.340300e+10   8.320200e+10   
1             85.7143  4.869300e+10   8.485900e+10   
2             62.0690  5.261000e+10   8.957300e+10   
3             25.0000  3.940100e+10   1.299270e+11   
4             19.5122  5.661700e+10   8.597800e+10   

   costofGoodsAndServicesSold  incomeTaxExpense  Forward_Return  \
0                6.779100e+10      9.480000e+08       26.207764   
1                6.937300e+10      8.040000e+08       -2.485423   
2                7.502200e+10      2.306000e+09       19.524858   
3                9.255300e+10      3.042000e+09       18.717916   
4                7.263300e+10      2.467000e+09        7.134934   

   Price_Movement_Class  
0                     4  
1                     1  
2                     4  
3                     4  
4                     4  

[5 rows x 36 columns]

# Step 3: EDA - Missing Values Analysis 

## Step 3)i): EDA - Show Missing Values in each Column

In [25]:
def display_columns_with_null_values(df: pd.DataFrame):
    """
    Displays the total number of null values for each column in the dataframe,
    showing only columns that have null values.
    
    Parameters:
    - df (pd.DataFrame): The dataframe to be checked for null values.
    
    Returns:
    - None: Prints the columns with null values and their counts.
    """
    
    # Get total null values in each column
    total_null_values = df.isnull().sum()
    
    # Filter out columns that don't have any null values
    columns_with_null = total_null_values[total_null_values > 0].sort_values(ascending=False)
    
    # Check if there are any columns with null values
    if not columns_with_null.empty:
        print('-' * 64)
        print("Total null values in each column (only columns with null values)")
        print('-' * 64)
        print(columns_with_null)
    else:
        print('-' * 64)
        print("Total null values in each column (only columns with null values)")
        print('-' * 64)
        print("No columns have null values.")

In [26]:
# Get percentage of null values in each column
null_values_percentage = df.isnull().mean().round(4).mul(100).sort_values(ascending=False)
print('-' * 44)
print("Percentage(%) of null values in each column")
print('-' * 44)
print(null_values_percentage)
print('\n')

# Get total null values in each column
display_columns_with_null_values(df)


--------------------------------------------
Percentage(%) of null values in each column
--------------------------------------------
Open                              0.0
High                              0.0
inventory                         0.0
shortTermInvestments              0.0
otherCurrentAssets                0.0
retainedEarnings                  0.0
changeInOperatingLiabilities      0.0
changeInOperatingAssets           0.0
capitalExpenditures               0.0
changeInReceivables               0.0
changeInInventory                 0.0
surprisePercentage                0.0
grossProfit                       0.0
costOfRevenue                     0.0
costofGoodsAndServicesSold        0.0
incomeTaxExpense                  0.0
Forward_Return                    0.0
cashAndShortTermInvestments       0.0
Unemployment_Rate_Quarterly       0.0
Retail_Sales_Quarterly            0.0
Stochastic_Oscillator             0.0
Low                               0.0
Close                         

## Step 3)ii): EDA - Handling Missing Values

In [27]:
# Fill Null Values in the Remaining Columns with the average of the column
numeric_df = df.select_dtypes(include=[np.number]) # Select only numeric columns
numeric_df.fillna(numeric_df.mean(), inplace=True)  # Fill missing values in numeric columns with the column mean
df[numeric_df.columns] = numeric_df # Merge back with non-numeric columns if needed

# Get total null values in each column
display_columns_with_null_values(df)


----------------------------------------------------------------
Total null values in each column (only columns with null values)
----------------------------------------------------------------
No columns have null values.


# Step 4: EDA - Duplicate Values Analysis 

## Step 4)i): EDA - Show Duplicate Values Rows

In [28]:
# Get percentage of duplicate rows
total_rows = len(df)
duplicate_rows = df.duplicated().sum()
duplicate_percentage = (duplicate_rows / total_rows) * 100

print('-' * 48)
print("Percentage(%) of duplicate rows in the DataFrame")
print('-' * 48)
print(f"{duplicate_percentage:.2f}%")
print('\n')

# Get total number of duplicate rows
print('-' * 30)
print("Total number of duplicate rows")
print('-' * 30)
print(duplicate_rows)


------------------------------------------------
Percentage(%) of duplicate rows in the DataFrame
------------------------------------------------
0.00%


------------------------------
Total number of duplicate rows
------------------------------
0


# Step 5): EDA - BackTesting

In [29]:
import joblib
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

# Load the saved model
joblib_file = "Model/random_forest_model_pipeline.joblib"
loaded_model = joblib.load(joblib_file)


# Extract features and actual labels
features = df.drop(columns=['Price_Movement_Class']) 
actual_labels = df['Price_Movement_Class']

# Make predictions using the loaded model
predicted_labels = loaded_model.predict(features)

# Add predictions to the original DataFrame as a new column
df['Price_Movement_Class_Prediction'] = predicted_labels

df.head(15)  

Open        High         Low       Close      Volume       MA_21  \
0   85.459999  114.000000   81.430000  103.290001  4237140900   94.574424   
1  102.300003  131.490005   97.709999  130.360001  3899624000  109.537804   
2  130.820007  145.860001  123.040001  127.120003  3389452900  133.134233   
3  127.279999  155.630005  118.349998  151.940002  3181680200  137.242933   
4  151.539993  181.699997  144.050003  180.380005  2700335000  162.643059   
5  180.789993  199.839996  166.320007  193.250000  2622598800  182.068685   
6  193.490005  201.199997  151.610001  186.330002  2604113800  182.434695   

         RSI      MACD  Stochastic_Oscillator       ATR  ...  \
0  54.283704  1.411384              57.035177  2.624101  ...   
1  62.979858  3.396109              74.222630  2.199527  ...   
2  53.048983 -2.481221              52.517575  2.589117  ...   
3  57.185846  2.782032              69.167466  2.602857  ...   
4  59.673912  2.546693              71.302744  2.503677  ...   
5  53.876961  2.608010              60.945101  2.844399  ...   
6  50.993386  3.399506              57.869881  3.823794  ...   

   changeInReceivables  changeInInventory  surprisePercentage   grossProfit  \
0         1.521000e+09      -3.710000e+08           47.619000  4.340300e+10   
1        -5.167000e+09       2.373000e+09           85.714300  4.869300e+10   
2        -1.304035e+09      -8.080000e+08           62.069000  5.261000e+10   
3        -1.304035e+09      -2.643000e+09           25.000000  3.940100e+10   
4        -1.304035e+09      -1.776000e+09           19.512200  5.661700e+10   
5        -1.304035e+09       3.085000e+09           22.330100  5.955300e+10   
6        -1.304035e+09       5.510164e+08           32.289969  2.204919e+10   

   costOfRevenue  costofGoodsAndServicesSold  incomeTaxExpense  \
0   8.320200e+10                6.779100e+10      9.480000e+08   
1   8.485900e+10                6.937300e+10      8.040000e+08   
2   8.957300e+10                7.502200e+10      2.306000e+09   
3   1.299270e+11                9.255300e+10      3.042000e+09   
4   8.597800e+10                7.263300e+10      2.467000e+09   
5   8.828600e+10                7.378500e+10      1.767000e+09   
6   3.865521e+10                3.335348e+10      3.863387e+08   

   Forward_Return  Price_Movement_Class  Price_Movement_Class_Prediction  
0       26.207764                     4                                4  
1       -2.485423                     1                                0  
2       19.524858                     4                                4  
3       18.717916                     4                                4  
4        7.134934                     4                                4  
5       -3.580853                     1                                0  
6        7.778962                     0                                4  

[7 rows x 37 columns]

In [30]:
# Calculate performance metrics for multi-class classification
accuracy = accuracy_score(actual_labels, predicted_labels)
precision = precision_score(actual_labels, predicted_labels, average='macro')  # Average for multi-class
recall = recall_score(actual_labels, predicted_labels, average='macro')
conf_matrix = confusion_matrix(actual_labels, predicted_labels)

# Display the results
# print(f'Accuracy: {accuracy:.4f}')
# print(f'Precision (Macro): {precision:.4f}')
# print(f'Recall (Macro): {recall:.4f}')
print('Confusion Matrix:')
print(conf_matrix)
print('\nClassification Report:')
print(classification_report(actual_labels, predicted_labels))


Confusion Matrix:
[[0 0 1]
 [2 0 0]
 [0 0 4]]

Classification Report:
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.00      0.00      0.00         2
           4       0.80      1.00      0.89         4

    accuracy                           0.57         7
   macro avg       0.27      0.33      0.30         7
weighted avg       0.46      0.57      0.51         7

